version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: receitas_db
      POSTGRES_USER: postgres # Replace with your desired username
      POSTGRES_PASSWORD: postgres # Replace with your desired password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
 